resolver: lts-23.15

allow-newer: true
allow-newer-deps:
  - clash-protocols

extra-deps:
- github: clash-lang/clash-protocols
  commit: febb041c32fa678e7ddb7d0e976516a5c56b03fc
  subdirs:
  - clash-protocols-base
  - clash-protocols
- github: cchalmers/circuit-notation
  commit: 564769c52aa05b90f81bbc898b7af7087d96613d
